### ISSUE TITLE
Engineering 공통과정 제안입니다.

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/handbook#10]
#### 공통과정
이더리움 황서가 없는게 좀 의문이에요. 베이지 페이퍼 한번 봤는데, 구술로 잘 설명되어있긴 하지만, 수학적인 notation 이 부족하고, 황서의 모든 내용을 포함하고 있진 않더라구요. 가령 state transition 이 단계적으로 일어나는데, 그 부분이 상당히 간략히 설명되어있구요. 하지만 trie 같은건 설명 잘 해둔거같아서 보기 좋더라구요.

하지만 제가 생각하는 황서를 봐야하는 가장 큰 이유는 
1. mathematical notation
  - 노테이션을 알고 나면 추가적인 알고리즘 / 개념 이해는 더욱 빠르고 정확하게 가능
2. [gitter](https://gitter.im/ethereum/yellowpaper) 를 통한 질의응답 가능
3. beige paper 보다 업데이트가 빠름
  - zk-SNARK verification 이 비잔티움 포크 후 precompile contract 으로 추가될 것 같음
4. beige paper 보다 public review 가 더 잘됨
  - contributor 1명 뿐
입니다.

researcher 라면 황서정도는 필수적으로 넣어야될 것 같고 engineer 라면 반반 정도로 넣어야 될 것 같아요.

**Comment by ggs134** [comment]
일리있습니다.

[공통과정](https://github.com/Onther-Tech/handbook/blob/master/engineering/ENGINEERING.md#%EA%B3%B5%ED%86%B5%EA%B3%BC%EC%A0%95)에 넣었어요.

클로징 하겠습니다.
