### ISSUE TITLE
[인사] 휴가

### ISSUE THREAD

**Issue by joohyoung-kang** [Onther-Tech/handbook#19]
### 휴가

- 휴가는 허가가 아닌 통보
- 1개월 만근 시 1일 휴가 (인턴 기간 포함)
- 0.5일 씩도 사용가능 (오전반차: 10:00 ~15:00 , 오후반차: 15:00 ~19:00)
- 팀원 휴가 시 부득이한 경우를 제외하고는 업무와 관련되어 연락하지 않는다.
- 사용방법
1. 연가를 원하는 사람은 언제든 지원팀에 얘기한다. (슬랙 DM, 이메일 등)
2. 지원팀은 팀장 및 대표에게 바로 전달
3. 지원팀은 슬랙채널 #notice 에 휴가신청이 완료됐음을 공지한다.
- 다만 주요한 일정으로 인해 휴가일정 조정이 권유될 수 있다.
- 휴가 요청 후 본인은 곧바로 온더 캘린더에 시간없는 일정으로 반영(노란색 라벨)
- 예비군 등도 동일 (연가는 사라지지 않음, 증명서 필요)

**Comment by ggs134** [comment]
https://github.com/Onther-Tech/handbook/blob/master/human/HUMAN.md#%ED%9C%B4%EA%B0%80%EC%99%80-%EC%89%AC%EB%8A%94%EA%B2%83
