### ISSUE TITLE
테스트테스트

### ISSUE THREAD

**Issue by joohyoung-kang** [Onther-Tech/handbook#2]
테스트를 해보겠다

**Comment by khk77** [comment]
# 일반사항 ## 가치에서
가치의 순서와 관련해서 여러가지 생각이 드는데, 자주 자주 다시 읽어보고 수정/추가/삭제 해야할 듯.
> 투명성??? --> 공유 or 시작으로 변경 아니면, 소제목으로 추가
 /"온더인"의 마인드Set, 
/동료/조직에 대한 Compassion의 마음으로 공유한다.
/이슈를 공개하고 공유하고 소통한다. 
/동료/조직의 성장을 위한 대안있는 비판과 피드백-> 수용-> 노력/해결 -> 성장
> 결과물
  /기록: (1)소통을 위해 최대한 친절하게 기록을 남긴다. (2)목표를 관리한다. (3)내 정리를 위해 기록한다.
> 성장 : 협동의8.스스로 하기는 성장에 속해야 하지 않나?
 /시작: 필요를 인식하면, 불만보다는 내가 먼저 시작하면 된다. 고민보다는 일단 그냥 시작한다. 이를 도와줄 동료가 옆에 있다. 
 /배가(doubling): 동료/조직의 성장이 나의 성장이다. 
> 효율성
> 협동(인성)
 /서로에 대한 관심 & 감사 & 사랑 
 / 피드백: 눈감아 주는게 사랑은 아니다. 적절한 피드백이 없는 것은 서로의 성장을 저해하는 것이다.

**Comment by ggs134** [comment]
테스트 성공한 것으로 보이니 클로징합니다.
