### ISSUE TITLE
Engineering guide 의견

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/handbook#4]
[엔지니어링 문서](https://github.com/Onther-Tech/handbook/blob/master/engineering/ENGINEERING.md) 에 관한 의견입니다.

##### 온더 레포지토리
각 레포지토리 당 maintainer 할당 필요. maintainer 는 쉽게 말하면 해당 저장소의 주 개발자. 소스 코드의 구조, 사용된 Framework, 개발 환경 등 저장소에 포함된 모든 내용물들을 숙지해야하는 의무가 있음. maintainer 가 필요한 이유는 개발 뿐만 아니라 소스코드 이해도가 높으면서 issue / pull request 를 담당할 역할이 필요하기 때문

따라서 해당 maintainer 외 개발자들은 pull request 를 통해서만 기여해야함. maintainer 는 pull request 를 통하지 않고 직접 commit 하도록 허용. 이는 code review 를 제안하는 방식과 담당할 사람을 명확히 구분해줌.

##### 코드리뷰
[github pull requests](https://github.com/Onther-Tech/handbook/pulls) 를 통해 기능 추가 제안 / 코드 리뷰 작성을 추천함.

maintainer 가 아니라면 항상 pull request 를 통해서 개발에 기여해야함. 이는 변경 사항을 maintainer 가 항상 추적할 수 있도록 도와주며, review 할 대상 커밋들을 [github pull requests](https://github.com/Onther-Tech/handbook/pulls) 에서 간략히 볼 수 있으며, 커뮤니케이션 또한 같은 UI 에서 이뤄질 수 있음.

**Comment by ggs134** [comment]
이런식으로 정리해볼게 의견을 줘ㅎ

**온더 레포지토리**
* 모든 레포지토리는 하나의 프로젝트에 속해있고(프로젝트는 여러개의 레포지토리를 가질 수 있음, EX) tokyo-cli, tokyo-diagram, tokyo-generater는 모두 tokyo의 하위 프로젝트
* 프로젝트는 프로젝트 오너(owner), 메인테이너(maintainer), 리뷰어(reviewer) 등 최소한 3개 이상의 롤을 가진 팀으로 구성하는 것을 제안, 각각의 레포지토리는 이 롤을 그대로 상속함.
  * 프로젝트 오너 : 프로젝트의 목적과 비전을 제시하고, 주요 자원을 할당하고, 업무의 우선순위를 정하고 일정을 제어
  * 메인테이너 : 메인 개발자. 소스 코드의 구조, 사용된 Framework, 개발 환경 등 저장소에 포함된 모든 내용물들을 숙지, 특히나 *pull request*를 통한 merge여부를 최종 결정함. 메인테이너는 직접 commit
  * 리뷰어 : 다수의 이슈와 리뷰가 동시다발적으로 이뤄질 때, 메인테이너를 보조하는 역할. 이슈 트레킹, pull request에 대한 의견을 내고 메인테이너를 계속 멘션하여 프로젝트 진행을 도움.
  * 이외의 모든 기여(commit)는 팀 내외부 누구나 할 수 있음

**코드리뷰**

good

이 구조는 이번 [핸드북](https://github.com/Onther-Tech/handbook) 프로젝트에도 반영할게
