### ISSUE TITLE
슬랙 공개 링크 # general_guests 관련

### ISSUE THREAD

**Issue by khk77** [Onther-Tech/handbook#5]
[엔지니어링에서 커뮤니케이션 부분](https://github.com/Onther-Tech/handbook/blob/master/engineering/ENGINEERING.md#%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98)
- 슬랭 공개 링크가 있던데,
- #general_guests 내용 public으로 오픈되어있는데,, 내용 clean해야 하지 않나요?

**Comment by ggs134** [comment]
지금 어차피 초대링크 없으면, public채널이라도 못들어옵니다.
#general_guests내용은 자동화 툴로 지워야되는데, 생각보다 귀찮고 오래 걸리는 작업이라 차차 하는걸로..
