### ISSUE TITLE
월간회의 초안

### ISSUE THREAD

**Issue by joohyoung-kang** [Onther-Tech/handbook#6]
### 월간회의
월간회의는 해당월 한 일에 대해서 이야기하고, 차월 할 일에 대해서 이야기 한다. 연간계획에 맞추어 계획대로 이루어지나 점검하는 시간이다. 지원팀의 재무활동 월간보고를 통해 회사내부사정을 공유하고 향후 방향성에 대해 토의한다. 또한 팀원들의 해당 월 정성평가가 이루어진다.

1. 월간회의는 기본적으로 매월 마지막 주 금요일 주간회의 다음에 이루어진다.
    - 시간: 오후 6시~
2. 필요 시 담당자는 회의실을 빌려놓는다. 희의실 장소 통보는 슬랙채널 #notice 에 {[가칭]슬랙사용법 notice}에 따라 작성한다.
3. 참여하지 못하는 사람은 "화상통화"로 참여한다.
4. 월간회의에 참여하기 전 각 팀 팀장은 주간회의 스프레드시트를 작성한다.
    - 양식의 위치는 구글드라이브 Onther- 6.관리 - 6-4 회의록 - 6-4-3. 주간회의
    - 양식의 제목은 "해당월 DM-WM-MM" 이다.
5. 월간회의에서는 해당월의 어젠다와 차월의 어젠다에 대해 이야기 한다.
5-1 그해 마지막 12월의 월간회의에서는 연간회의를 겸한다.
6. 지원팀은 재무보고를 한다. 온더의 내부사정을 모두 공유하고 투명하게 경영을 이끌어가기 위함이다. 
6-1 해당월의 지출현황, 매출액현황, 향후 6~1년 재무현황에 대해 이야기 한다.
6-2 마지막 12월의 경우 연간 재무현황에 대해 이야기 한다.
7. 월간회의에서는 모든 팀원의 "성과평가"가 이루어진다.

**Comment by ggs134** [comment]
주간회의 2번에 

< {[가칭]슬랙사용법 notice}에 따라 작성한다.>

여기에는 어떤 내용이 들어가야될까요?

**Comment by ggs134** [comment]
한 이슈에 하나씩 올려주실  수 있나요? 꼭지가 많으니까 한번에 클로징 하기 힘드네요..

**Comment by joohyoung-kang** [comment]
슬랙사용법 notice 형식을 지정해둬야 할거 같아서요~.
"월/일"  ("요일") "시간" "내용" "장소" "@name" 와 같은 형식으로 공지한다.
ex: 4/13(금) 오전10:00~11:00 깃헙 사용 교육, 4층 Peridot @Kevin

그리고 넵  한 이슈에 하나씩 올릴게요.
