### ISSUE TITLE
일반사항에 대한 피드백

### ISSUE THREAD

**Issue by khk77** [Onther-Tech/handbook#7]
> [googleDrive 매뉴얼 작성(진행중)](https://docs.google.com/document/d/13RODuuprXEJYqo8-sX2Ltob29vsO9gIO93OsMIaes4s/edit)

- 용어통일: 슬렉 vs 슬랙

> [내부 커뮤니케이션](https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%EB%82%B4%EB%B6%80-%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98)
- 멘션에 @추가
- +바로 답장이 안올경우, 언제든 음성연결을 시도한다. 

> [채팅](https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%EC%B1%84%ED%8C%85)
- 투두봇—> todo 추가

> [일일회의](https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%EC%9D%BC%EC%9D%BC%ED%9A%8C%EC%9D%98)
- 자신의 일정은 스스로 계획한다.

**Comment by ggs134** [comment]
* 슬렉으로 용어 통일
* todobot으로 모두 변경
* 내용 추가함
