### ISSUE TITLE
카테고리 '세미나' 추가 제안

### ISSUE THREAD

**Issue by khk77** [Onther-Tech/handbook#8]
> [프레젠테이션](https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%ED%94%84%EB%A0%88%EC%A0%A0%ED%85%8C%EC%9D%B4%EC%85%98) 혹은 [커뮤니케이션](https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%EC%BB%A4%EB%AE%A4%EB%8B%88%EC%BC%80%EC%9D%B4%EC%85%98)에

카테고리로 “세미나”추가 하면 좋을 것같아요.
1 세미나 주제 정하기
2 캘린더에 일정 추가
3 #notice 공지
   3.1 날짜(요일), 세미나 내용, 장소, 시간, @이름, 발표자료 링크
   3.2 (예시) 4/6(금), EVM구조, 6층Onyx, 오후6시~7시, @Tom, 발표자료링크

4 세미나/녹화 준비
   4.1 빠른 피드백을 위해 세미나자료(프레젠테이션/문서 등 관련 링크) 생성시에는 링크를 바로 공유한다.
세미나 전 준비
   4.2 화상 채팅 링크는 세미나 최소 5분전에 링크를 공유한다.
   4.3 서로의 시간을 save하기 위해, 세미나 전 영상 테스트, 세미나 주제, 논의 아젠다 등은 미리 준비 한다.

**Comment by ggs134** [comment]
추가했습니다.

https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%EC%84%B8%EB%AF%B8%EB%82%98

내용은 조금 수정됬어요.
