### ISSUE TITLE
녹화 초안

### ISSUE THREAD

**Issue by joohyoung-kang** [Onther-Tech/handbook#9]
녹화는 팀콜, 세미나, 일일회의, 주간회의, 월간회의 때 의무적으로 녹화한다. 주최자가 녹화하는 것을 원칙으로 하며 부득이한 경우 참여자 중 한 명이 녹화한다. 녹화의 목적은  두 가지다. 위 상황에 참여하지 못한 구성원이 차후에 정보를 습득하기 위함이고, 기록을 남겨 결과물 성과물로 남겨놓기 위함이다. 
녹화의 프로세스는  1.Appear에 접속하여 화상채팅을 시작하고 2.HYFY를 사용하여 녹화를 진행하는 순서이다. 또한 녹화 후 해당링크를 리스트에 작성하여 구성원 모두에게 공유한다.

**Comment by ggs134** [comment]
녹화는 녹화에 관한 일반사항(언제, 왜 녹화하는지, 어떤 상황에 녹화하는지 등)을 적고,
아래 HYFY등은 [도구](https://github.com/Onther-Tech/handbook/blob/master/general/GENERAL.md#%EB%8F%84%EA%B5%AC)에 들어가야 하지 않을까요?

**Comment by joohyoung-kang** [comment]
저는 녹화에서 통합해서 쓰려고 했는데 그게 더 나을거 같네요.!
